# Generated by Django 4.2 on 2024-11-16 00:21

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('icon', models.CharField(max_length=64)),
                ('participants', models.ManyToManyField(related_name='own_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
