# Generated by Django 4.2 on 2024-11-25 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0002_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='participants',
        ),
        migrations.CreateModel(
            name='UserAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='splitwise_clone.usergroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
