# Generated by Django 4.2 on 2024-11-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0003_remove_usergroup_participants_useralias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='icon',
            field=models.CharField(default='💸', max_length=64),
        ),
    ]
