# Generated by Django 4.2 on 2024-12-01 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
