# Generated by Django 4.2 on 2024-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0006_expense_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='icon',
            field=models.CharField(default='💳', max_length=64),
        ),
    ]
