# Generated by Django 4.2 on 2024-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0007_expense_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Us Dollar')], default='EUR', max_length=3),
        ),
    ]
