# Generated by Django 4.2 on 2024-12-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_clone', '0008_alter_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_expenses', to='splitwise_clone.usergroup'),
        ),
    ]
